server:
  port: 8080

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000


ribbon:
  ServerListRefreshInterval: 15000

zuul:
  ignored-services: "*"
  routes:
    customers:
      path: /customers/**
      serviceId: customer-service
      stripPrefix: false
    check-load-balance:
      path: /check-load-balancing
      serviceId: customer-service
      stripPrefix: false

spring:
  application:
    name: gateway-service

management:
  security:
    enabled: false



